name: climate-rl-mres
channels:
  - pytorch
  - nvidia
  - conda-forge
  - intel
dependencies:
  - climlab
  - ipython
  - jupyter
  - metpy
  - numpy
  - moviepy
  - gymnasium
  - pygame
  - python=3.11
  - pytorch-cuda
  - pytorch
  - ray-default
  - ray-tune
  - stable-baselines3 
  - tensorboard
  - tephi
  - torchaudio
  - torchvision
  - tqdm
  - tyro
  - wandb